// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { registerApiMethod } from '../tools';
import ModernTreasury from 'modern-treasury';

registerApiMethod({
  name: 'retrieve_incoming_payment_details',
  description: 'Get an existing Incoming Payment Detail.',
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
    },
  },
  handler: (client: ModernTreasury, args: any) => {
    const { id } = args;
    return client.incomingPaymentDetails.retrieve(id);
  },
});

registerApiMethod({
  name: 'update_incoming_payment_details',
  description: 'Update an existing Incoming Payment Detail.',
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
      },
      metadata: {
        type: 'object',
        description:
          'Additional data in the form of key-value pairs. Pairs can be removed by passing an empty string or `null` as the value.',
      },
    },
  },
  handler: (client: ModernTreasury, args: any) => {
    const { id, ...body } = args;
    return client.incomingPaymentDetails.update(id, body);
  },
});

registerApiMethod({
  name: 'list_incoming_payment_details',
  description: 'Get a list of Incoming Payment Details.',
  inputSchema: {
    type: 'object',
    properties: {
      after_cursor: {
        type: 'string',
      },
      as_of_date_end: {
        type: 'string',
        description:
          'Filters incoming payment details with an as_of_date starting on or before the specified date (YYYY-MM-DD).',
        format: 'date',
      },
      as_of_date_start: {
        type: 'string',
        description:
          'Filters incoming payment details with an as_of_date starting on or after the specified date (YYYY-MM-DD).',
        format: 'date',
      },
      direction: {
        type: 'string',
        enum: ['credit', 'debit'],
      },
      metadata: {
        type: 'object',
        description:
          'For example, if you want to query for records with metadata key `Type` and value `Loan`, the query would be `metadata%5BType%5D=Loan`. This encodes the query parameters.',
      },
      per_page: {
        type: 'integer',
      },
      status: {
        type: 'string',
        description:
          'The current status of the incoming payment order. One of `pending`, `completed`, or `returned`.',
        enum: ['completed', 'pending', 'returned'],
      },
      type: {
        type: 'string',
        description: 'One of: `ach`, `book`, `check`, `eft`, `interac`, `rtp`, `sepa`, `signet`, or `wire`.',
        enum: [
          'ach',
          'au_becs',
          'bacs',
          'book',
          'check',
          'eft',
          'interac',
          'neft',
          'nz_becs',
          'rtp',
          'sepa',
          'signet',
          'wire',
        ],
      },
      virtual_account_id: {
        type: 'string',
        description: 'If the incoming payment detail is in a virtual account, the ID of the Virtual Account.',
      },
    },
  },
  handler: (client: ModernTreasury, args: any) => {
    const { ...body } = args;
    return client.incomingPaymentDetails.list(body);
  },
});

registerApiMethod({
  name: 'create_async_incoming_payment_details',
  description: 'Simulate Incoming Payment Detail',
  inputSchema: {
    type: 'object',
    properties: {
      amount: {
        type: 'integer',
        description: "Value in specified currency's smallest unit. e.g. $10 would be represented as 1000.",
      },
      as_of_date: {
        type: 'string',
        description: 'Defaults to today.',
        format: 'date',
      },
      currency: {
        type: 'string',
        description: 'Three-letter ISO currency code.',
        enum: [
          'AED',
          'AFN',
          'ALL',
          'AMD',
          'ANG',
          'AOA',
          'ARS',
          'AUD',
          'AWG',
          'AZN',
          'BAM',
          'BBD',
          'BCH',
          'BDT',
          'BGN',
          'BHD',
          'BIF',
          'BMD',
          'BND',
          'BOB',
          'BRL',
          'BSD',
          'BTC',
          'BTN',
          'BWP',
          'BYN',
          'BYR',
          'BZD',
          'CAD',
          'CDF',
          'CHF',
          'CLF',
          'CLP',
          'CNH',
          'CNY',
          'COP',
          'CRC',
          'CUC',
          'CUP',
          'CVE',
          'CZK',
          'DJF',
          'DKK',
          'DOP',
          'DZD',
          'EEK',
          'EGP',
          'ERN',
          'ETB',
          'EUR',
          'FJD',
          'FKP',
          'GBP',
          'GBX',
          'GEL',
          'GGP',
          'GHS',
          'GIP',
          'GMD',
          'GNF',
          'GTQ',
          'GYD',
          'HKD',
          'HNL',
          'HRK',
          'HTG',
          'HUF',
          'IDR',
          'ILS',
          'IMP',
          'INR',
          'IQD',
          'IRR',
          'ISK',
          'JEP',
          'JMD',
          'JOD',
          'JPY',
          'KES',
          'KGS',
          'KHR',
          'KMF',
          'KPW',
          'KRW',
          'KWD',
          'KYD',
          'KZT',
          'LAK',
          'LBP',
          'LKR',
          'LRD',
          'LSL',
          'LTL',
          'LVL',
          'LYD',
          'MAD',
          'MDL',
          'MGA',
          'MKD',
          'MMK',
          'MNT',
          'MOP',
          'MRO',
          'MRU',
          'MTL',
          'MUR',
          'MVR',
          'MWK',
          'MXN',
          'MYR',
          'MZN',
          'NAD',
          'NGN',
          'NIO',
          'NOK',
          'NPR',
          'NZD',
          'OMR',
          'PAB',
          'PEN',
          'PGK',
          'PHP',
          'PKR',
          'PLN',
          'PYG',
          'QAR',
          'RON',
          'RSD',
          'RUB',
          'RWF',
          'SAR',
          'SBD',
          'SCR',
          'SDG',
          'SEK',
          'SGD',
          'SHP',
          'SKK',
          'SLL',
          'SOS',
          'SRD',
          'SSP',
          'STD',
          'SVC',
          'SYP',
          'SZL',
          'THB',
          'TJS',
          'TMM',
          'TMT',
          'TND',
          'TOP',
          'TRY',
          'TTD',
          'TWD',
          'TZS',
          'UAH',
          'UGX',
          'USD',
          'UYU',
          'UZS',
          'VEF',
          'VES',
          'VND',
          'VUV',
          'WST',
          'XAF',
          'XAG',
          'XAU',
          'XBA',
          'XBB',
          'XBC',
          'XBD',
          'XCD',
          'XDR',
          'XFU',
          'XOF',
          'XPD',
          'XPF',
          'XPT',
          'XTS',
          'YER',
          'ZAR',
          'ZMK',
          'ZMW',
          'ZWD',
          'ZWL',
          'ZWN',
          'ZWR',
        ],
      },
      data: {
        type: 'object',
        description:
          'An object passed through to the simulated IPD that could reflect what a vendor would pass.',
      },
      description: {
        type: 'string',
        description: 'Defaults to a random description.',
      },
      direction: {
        type: 'string',
        description: 'One of `credit`, `debit`.',
        enum: ['credit', 'debit'],
      },
      internal_account_id: {
        type: 'string',
        description: 'The ID of one of your internal accounts.',
      },
      type: {
        type: 'string',
        description: 'One of `ach`, `wire`, `check`.',
        enum: [
          'ach',
          'au_becs',
          'bacs',
          'book',
          'check',
          'eft',
          'interac',
          'neft',
          'nz_becs',
          'rtp',
          'sepa',
          'signet',
          'wire',
        ],
      },
      virtual_account_id: {
        type: 'string',
        description: 'An optional parameter to associate the incoming payment detail to a virtual account.',
      },
    },
  },
  handler: (client: ModernTreasury, args: any) => {
    const { ...body } = args;
    return client.incomingPaymentDetails.createAsync(body);
  },
});
